### ISSUE TITLE
No way to get the raw Uri or Url from the request including unparsed querystring

### ISSUE THREAD

**Issue by Epictek** [dom96/jester#145]

**Comment by dom96** [comment]
Hrm, so I'm now wondering: what's the use case for this?

As far as I can tell Sinatra doesn't expose this either.

**Comment by Epictek** [comment]
The use case was just getting the unparsed query string to proxy to a HTTP request. It's not a big issue just would be nice to have. Guess I'm just too used to using Flask http://flask.pocoo.org/docs/1.0/api/#incoming-request-data.

Sinatra also seems to expose a lot more infomation: https://gist.github.com/taktran/1443262

**Comment by dom96** [comment]
Am I just blind or does Sinatra not expose this? I don't see it in your link.

**Comment by Epictek** [comment]
request.path? I've never  used sinatra so I'm not sure how it works exactly

**Comment by dom96** [comment]
> request.path                # "/example/foo"

That just returns the path, not the full URI

**Comment by alehander42** [comment]
I might be mistaken, but it seems one has to patch httpbeast for that

Btw, why is it so important if sinatra does something or not? Jester is not nim-sinatra

**Comment by alehander42** [comment]
Well, if a sinatra user misses functionality, the explanation might be that they just go with Rails, Nim doesn't have a Rails yet

**Comment by dom96** [comment]
So develop a Rails. Don't expect me to turn Jester into Rails.

**Comment by alehander42** [comment]
I am just explaining that it makes more sense for Sinatra to make certain design/feature decisions.

I love that you're trying to keep Jester minimal.  However I don't think "not exposing" stuff is what defines a minimal framework(or turning it to Rails), totally the opposite. A good mini framework should expose a small powerful core which is sufficient for people to develop on top of. 

In this case each feature request can be answered with: you can do this, you just have to write it yourself. (This is the difference with a big framework which would try to include plugins and helpers and dsl-s for everything you might need).
If the answer is "well, you can't do this, full stop", this is too limiting for no gain: it doesn't simplify the framework and it just makes the user's life harder.

(Otherwise I'd love if somebody does a "Rails" too, but I prefer to contribute to Jester, so we have at least one very cool lib instead of several kinda-there libs)

**Comment by Araq** [comment]
> So develop a Rails. Don't expect me to turn Jester into Rails.

Nim already has a grumpy old man (me), you're the good cop, remember? :-)
